# Generated by Django 5.0.6 on 2024-06-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='Home.CartItem', to='Home.product'),
        ),
    ]
