# Generated by Django 5.0.6 on 2024-07-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_orders_customer_remove_orders_product_and_more'),
        ('Home', '0006_remove_cart_total_cart_items'),
    ]

    operations = [
    ]
